In [64]:
from google.colab import drive
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics as metrics

# for easier reading np
np.set_printoptions(precision=3,suppress=True)

In [65]:
drive.mount('/content/drive')
with open('/content/drive/My Drive/Colab Notebooks/data/winequality-red.csv', 'r') as f: 
  temp = np.genfromtxt(f,delimiter=',',skip_header=1)
  X = temp[:,:-1]
  y = temp[:,-1]
  Labels = np.unique(y)   # class labels
  print('Class labels are: ', Labels)

Mounted at /content/drive
Class labels are:  [3. 4. 5. 6. 7. 8.]


In [66]:
# 80/20 train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print('Training dataset size: ', np.shape(X_train))
print('Testing dataset size: ', np.shape(X_test))

Training dataset size:  (1279, 11)
Testing dataset size:  (320, 11)


In [67]:
, NearestNeighbors
# Develop the kNN model using 3-fold CV for 1 to 9 neighbors
kcv = 3
for nb in range(9):
  kNNmodel = KNeighborsClassifier(n_neighbors = nb+1)
  cv_score = np.mean(cross_val_score(kNNmodel, X_train, y_train, cv = kcv))
  print(nb+1, " nearest neighbors, 3-fold CV mean accuracy = ", format(cv_score, ".3f"))

1  nearest neighbors, 3-fold CV mean accuracy =  0.539
2  nearest neighbors, 3-fold CV mean accuracy =  0.493
3  nearest neighbors, 3-fold CV mean accuracy =  0.482
4  nearest neighbors, 3-fold CV mean accuracy =  0.493
5  nearest neighbors, 3-fold CV mean accuracy =  0.496
6  nearest neighbors, 3-fold CV mean accuracy =  0.486
7  nearest neighbors, 3-fold CV mean accuracy =  0.492
8  nearest neighbors, 3-fold CV mean accuracy =  0.503
9  nearest neighbors, 3-fold CV mean accuracy =  0.507


In [68]:
# Use the # neighbors that gives highest 3-fold CV mean accuracy to develop a model
kNNmodel = KNeighborsClassifier(n_neighbors = 1)
kNNmodel.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix
y_pred = kNNmodel.predict(X_test)
print("Confusion matrix: \n",confusion_matrix(y_test, y_pred))
print('Classification Rate of %i neighbors: %f \n'% (nb+1,metrics.accuracy_score(y_test,y_pred)))

Confusion matrix: 
 [[ 0  2  0  0  1  0]
 [ 1  0  4  7  1  0]
 [ 1  4 93 37  3  1]
 [ 0  1 35 73 12  0]
 [ 0  0  8  9 23  0]
 [ 0  0  0  2  2  0]]
Classification Rate of 9 neighbors: 0.590625 



In [69]:
print('Classification Rate of %i neighbors: %f \n'% (nb+1,metrics.accuracy_score(y_test,y_pred)))

Classification Rate of 9 neighbors: 0.590625 



In [70]:
drive.flush_and_unmount()